require("dotenv").config({ path: "test.env" });

const OPENMRS_URL = `${process.env.APPLICATION_URL}/openmrs`;
const REST_API_URL = `${process.env.APPLICATION_URL}/openmrs/ws/rest/v1`;
const BAHMNI_URL = `${process.env.APPLICATION_URL}/bahmni`;
const BAHMNI_LOGIN_URL = `${process.env.APPLICATION_URL}/bahmni/home/index.html#/login`;
const ADMIN_USERNAME = process.env.ADMIN_USERNAME;
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;
const DEFAULT_TEST_LOCATION = "OPD-1";
const DEFAULT_PATIENT_IDENTIFIER_TYPE = "81433852-3f10-11e4-adec-0800271c1b75";

module.exports = {
  OPENMRS_URL: OPENMRS_URL,
  REST_API_URL: REST_API_URL,
  BAHMNI_URL: BAHMNI_URL,
  BAHMNI_LOGIN_URL: BAHMNI_LOGIN_URL,
  ADMIN_USERNAME: ADMIN_USERNAME,
  ADMIN_PASSWORD: ADMIN_PASSWORD,
  DEFAULT_TEST_LOCATION: DEFAULT_TEST_LOCATION,
  DEFAULT_PATIENT_IDENTIFIER_TYPE: DEFAULT_PATIENT_IDENTIFIER_TYPE
};
